apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-data-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/host/notebook"
