version: "3.6"
volumes:
  shared-dir:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: itsayushthada/jupyter-lab:v1
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-dir:/opt/notebook
  spark-master:
    image: itsayushthada/spark-master:v1
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-dir:/opt/notebook
  spark-worker-1:
    image: itsayushthada/spark-worker:v1
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - shared-dir:/opt/notebook
    depends_on:
      - spark-master
  spark-worker-2:
    image: itsayushthada/spark-worker:v1
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - shared-dir:/opt/notebook
    depends_on:
      - spark-master
  localstack:
    image: "localstack/localstack:0.12.2"
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      - HOSTNAME_EXTERNAL="s3.localstack"
      - SERVICES=s3      
    depends_on:
      - spark-master
